Repository googleads/publisher-ads-lighthouse-plugin, pull requests merged in 2021-02, with the labels that each got.

#253 Adding docs for GPT API audits
  docs/audits/deprecated-api-usage.md
  docs/audits/gpt-errors-overall.md
Labels: cla: yes, v1.4

#257 Set version to v1.4.1.
  lighthouse-plugin-publisher-ads/package.json
  package.json
Labels: cla: yes

#259 Upgrade to LH v7.1.0
  lighthouse-plugin-publisher-ads/package.json
  package.json
  yarn.lock
Labels: cla: yes, v1.5

#245 Set up example Lighthouse CI and documentation.
  .github/workflows/ci.yml
  .gitignore
  lighthouse-ci/README.md
  lighthouse-ci/mock-pages/fast-ads.html
  lighthouse-ci/mock-pages/slow-ads.html
  lighthouse-ci/mock-pages/slowly-inject-gpt.js
  lighthouse-plugin-publisher-ads/README.md
  lighthouserc.js
  package.json
  yarn.lock
Labels: cla: yes
