Repository googleads/publisher-ads-lighthouse-plugin, pull requests merged in 2021-06, with the labels that each got.

#272 New audit for a total ad blocking time metric
  lighthouse-plugin-publisher-ads/audits/total-ad-blocking-time.js
  lighthouse-plugin-publisher-ads/messages/en-US.json
  lighthouse-plugin-publisher-ads/messages/locales/en-XL.json
  lighthouse-plugin-publisher-ads/plugin.js
  lighthouse-plugin-publisher-ads/test/smoke/expectations/not-applicable.js
  lighthouse-plugin-publisher-ads/utils/resource-classification.js
Labels: cla: yes

#276 Include pubads_impl in the critical path
  lighthouse-plugin-publisher-ads/audits/ad-request-critical-path.js
Labels: cla: yes

#274 Update cumulative ad shift computation
  lighthouse-plugin-publisher-ads/audits/cumulative-ad-shift.js
  lighthouse-plugin-publisher-ads/test/smoke/expectations/cumulative-ad-shift.js
  lighthouse-plugin-publisher-ads/test/smoke/fixtures/layout-shift.html
  lighthouse-plugin-publisher-ads/test/smoke/smoke-test-dfns.js
Labels: cla: yes

#278 Migrate from Travis CI to GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: cla: yes

#279 Limit cumulative ad shift measurement to a session window
  lighthouse-plugin-publisher-ads/audits/cumulative-ad-shift.js
Labels: cla: yes

#273 Add logic to make API audits not-applicable if no impl is found + audit rename
  lighthouse-plugin-publisher-ads/audits/deprecated-api-usage.js
  lighthouse-plugin-publisher-ads/audits/gpt-errors-overall.js
  lighthouse-plugin-publisher-ads/test/smoke/expectations/not-applicable.js
Labels: audit, cla: yes

#280 Upgrade to v1.4.2
  lighthouse-plugin-publisher-ads/package.json
  package.json
Labels: cla: yes

#281 Show waterfall on pages without ad requests
  lighthouse-plugin-publisher-ads/utils/graph.js
  lighthouse-plugin-publisher-ads/utils/resource-classification.js
Labels: cla: yes

#282 Upgrade to LH v8
  lighthouse-plugin-publisher-ads/package.json
  lighthouserc.js
  package.json
  yarn.lock
Labels: cla: yes

#283 Upgrade to v1.5.0
  lighthouse-plugin-publisher-ads/package.json
  package.json
Labels: cla: yes

#286 Document total ad blocking time audit
  docs/audits/total-ad-blocking-time.md
  lighthouse-plugin-publisher-ads/audits/total-ad-blocking-time.js
  lighthouse-plugin-publisher-ads/messages/en-US.json
  lighthouse-plugin-publisher-ads/messages/locales/en-XL.json
Labels: cla: yes, ready to pull
